QDRANT_URL        = "http://localhost:6333"
QDRANT_COLLECTION = "greenrag_docs"
EMBEDDING_MODEL   = "BAAI/bge-m3"
EMBEDDING_DIM     = 1024
CHUNK_SIZE        = 1800
CHUNK_OVERLAP     = 200
LLM_MODEL = "llama3.2:3b"
OLLAMA_URL        = "http://localhost:11434"
DATA_PATH         = "data/raw"
SOURCES           = ["irena", "iea", "owid"]